apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  labels:
    team: tsm
    system: mottak
  name: regdump
  namespace: tsm
spec:
  acl:
    - team: tsm
      application: migrator
      access: read
    - team: teamsykmelding
      application: macgyver
      access: write
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 3
    partitions: 10
    replication: 3
    retentionBytes: -1
    retentionHours: -1
  pool: {{kafka-pool}}
