apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  labels:
    team: tsm
  name: sykmeldinger
  namespace: tsm
spec:
  acl:
    - team: tsm
      application: regulus-maximus
      access: readwrite
    - team: disykefravar
      application: dvh-sykefravar-airflow-kafka
      access: read
  config:
    cleanupPolicy: compact
    minimumInSyncReplicas: 3
    partitions: 10
    replication: 3
    retentionBytes: -1
    retentionHours: -1
  pool: {{kafka-pool}}
