apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  labels:
    team: tsm
    system: mottak
  name: teamsykmelding-sykmeldinger
  namespace: tsm
spec:
  acl:
    - team: tsm
      application: migrator
      access: readwrite
    - team: tsm
      application: sykmelding-bucket-upload
      access: read
  config:
    cleanupPolicy: compact
    minimumInSyncReplicas: 3
    partitions: 10
    replication: 3
    retentionBytes: -1
    retentionHours: -1
  pool: {{kafka-pool}}
