apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  labels:
    team: tsm
    system: mottak
  name: tsmsykmelding-raw
  namespace: tsm
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
spec:
  acl:
    - team: tsm
      application: regulus-maximus
      access: write
    - team: tsm
      application: tsm-gateway
      access: read
  config:
    cleanupPolicy: compact
    minimumInSyncReplicas: 3
    partitions: 10
    replication: 3
    retentionBytes: -1
    retentionHours: -1
  pool: {{kafka-pool}}
