name: deploy-topics-dev
on:
  push:
    branches:
      '**'
jobs:
  deploy-to-dev:
    name: Deploy to dev-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate topic files list
        id: generate-topics
        run: |
          FILES=$(find topics/ -type f -name '*.yml' | tr '\n' ',' | sed 's/,$//')
          echo "TOPIC_FILES=$FILES" >> $GITHUB_ENV
          echo "Files: $FILES"
      - name: Deploy topics to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          VAR: kafka-pool=nav-dev
          RESOURCE: ${{ env.TOPIC_FILES }}
