name: deploy-topics-dev
on:
  push:
    branch:
      '**'
env:
  TOPIC_FILES: topics/tier-1/mottak-sykmelding.yml
jobs:
  deploy-to-dev:
    name: Deploy to dev-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy topics to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          VAR: kafka-pool=nav-dev
          RESOURCE: ${{ env.TOPIC_FILES }}
        