name: deploy-topics-prod
on:
  push:
    branch:
      'main'
env:
  TOPIC_FILES: topics/tier-1/mottak-sykmelding.yml,topics/tier-temp/regdump.yml,topics/tier-1/migrert-sykmelding.yml,topics/tier-1/sykmeldinger-input.yml
jobs:
  deploy-to-prod:
    name: Deploy to prod-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy topics to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          VAR: kafka-pool=nav-prod
          RESOURCE: ${{ env.TOPIC_FILES }}
